# https://{{VCENTER}}/rest/vcenter/vm/{{VM}}

- name: delete VMs
  uri:
    url: "https://{{ vcenter.host }}/rest/vcenter/vm/{{vmStatus.json.value[0].vm}}"
    method: DELETE
    return_content: true
    validate_certs: false
    headers:
      vmware-api-session-id: "{{ vcenterToken.json.value }}"
    status_code: 200
  register: deleteResult
  retries: 3
  delay: 30
  delegate_to: localhost
  when: vmStatus.json.value != []
# - name: delete result
#   debug:
#     msg: "{{deleteResult}}"