- name: check for AS3
  uri: 
    url: "https://{{ provider.server }}{{ as3CheckUrl }}"
    method: GET
    headers:
      X-F5-Auth-Token: "{{ token.json.token.token }}"
    return_content: true
    validate_certs: false
    status_code: 200
  register: as3_checkStatus
  until: as3_checkStatus is success
  retries: 10
  delay: 30
  delegate_to: localhost
  when: token.json.token.token != ""